

# For the  gene "SIRT7" give me abstracts mentioned, and for all the authors,
# their patents, and then which protein complexes are mentioned in there, and give me the individual proteins

match 
$g isa gene, has gene-symbol "SIRT7"; 
$p isa paper;
$a isa person;
$patent isa patent; 
$pr isa paragraph;
$pr2 isa paragraph;
$r1 (mentioning-paragraph: $pr, mentioned: $g) isa mentioning;
$r2 (contained-paper-paragraph: $pr, containing-paper: $p) isa paper-paragraph-containment;
$r3 (authored-paper: $p, author: $a) isa authorship; 
$r4 (inventor: $a, invented: $patent) isa invention; 
$r5 (containing-patent: $patent, contained-patent-paragraph: $pr2) isa patent-paragraph-containment;
$prcom (associated-protein: $protein, associated-protein: $protein2) isa protein-complex; 
$r6 (mentioning-paragraph: $pr2, mentioned: $prcom) isa mentioning; 
get; 

match 
$g isa gene, has gene-symbol "SIRT7"; 
$p isa paper;
$a isa person;
$patent isa patent; 
$pr isa paragraph;
$pr2 isa paragraph;
$r1 (mentioning-paragraph: $pr, mentioned: $g) isa mentioning;
$r2 (contained-paper-paragraph: $pr, containing-paper: $p) isa paper-paragraph-containment;
$r3 (authored-paper: $p, author: $a) isa authorship; 
$r4 (inventor: $a, invented: $patent) isa invention; 
$r5 (containing-patent: $patent, contained-patent-paragraph: $pr2) isa patent-paragraph-containment;
$prcom (associated-protein: $protein, associated-protein: $protein2) isa protein-complex; 
$r6 (mentioning-paragraph: $pr2, mentioned: $prcom) isa mentioning; 
$protein has uniprot-name $name;
get $name; 